# Numpy

## Indexing Array

In [1]:
# import numpy
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#Get a value at an index
arr[8]

8

In [5]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

#### Broadcasting

In [6]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
#Setting a value with index range (Broadcasting)
arr[0:5] = 100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
# Reset array, we'll see why i had to reset in a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### The broadcasting effect! 


In [9]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
#Change Slice
slice_of_arr[:] = 99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [11]:
# Now note the changes also occur in our original array!
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! **This avoids memory problems!**

In [12]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Indexing 2D-Array

In [13]:
# Indexing a 2D array
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

#### Grab the diagonal Diagonal

In [14]:
# Extract the diagonal of a given array
np.diag(arr_2d)

array([ 5, 25, 45])

In [15]:
# Upper diagonal
np.diag(arr_2d, k=1)

array([10, 30])

In [16]:
# Lower diagonal
np.diag(arr_2d, k=-1)

array([20, 40])

#### Indexing a 2-D array

In [17]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
#Indexing row
arr_2d[0]

array([ 5, 10, 15])

In [19]:
#Indexing row
arr_2d[2]

array([35, 40, 45])

To get an individual element value the format is **arr_2d[row][col]** or **arr_2d[row,col]**

In [20]:
# Grab a single value
arr_2d[1][0]

20

In [21]:
# alternatively
arr_2d[1,0]

20

In [22]:
arr_2d[1,2]

30

#### Slicing 2-D array

Getting a portion of the array

In [24]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
#Shape (2,2) from top right corner
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [26]:
# Shape (2,2) left down corner
arr_2d[1: , 0:2]

array([[20, 25],
       [35, 40]])

In [28]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [29]:
#Shape bottom row (second and third column)
arr_2d[2, 1:]

array([40, 45])

### Fancy Indexing

NumPy offers more indexing facilities than regular Python sequences. 

In addition to indexing by integers and slices, as we saw before, arrays can be indexed by arrays of integers and arrays of booleans.

In [33]:
#Set up 2d-array
array_2d = np.zeros((10,10))
array_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
#Length of array
arr_length = array_2d.shape[0]
arr_length

10

We can loop throgh the array and change the values

In [36]:
# In this case we change the values row by row
for i in range(arr_length):
    array_2d[i] = i
    
array_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [37]:
array_2d[1, 0]

1.0

#### Fancy indexing allows the following

In [38]:
# we create the array 
palette = np.array( [ [0,0,0],                # black
                      [255,0,0],              # red
                      [0,255,0],              # green
                      [0,0,255],              # blue
                      [255,255,255] ] )       # white

In [39]:
# the array we will use to indexing
image = np.array( [ 0, 2, 4 ])           # each value corresponds to a color in the palette 

In [40]:
# indexing

palette[image]

array([[  0,   0,   0],
       [  0, 255,   0],
       [255, 255, 255]])

In [41]:
# another example
image2 = np.array([[0,4],[1,4]])

palette[image2]

array([[[  0,   0,   0],
        [255, 255, 255]],

       [[255,   0,   0],
        [255, 255, 255]]])

## Let's exercise!