# Numpy

## Universal Array Functions

A universal function (or ufunc for short) is a function that operates on ndarrays in an element-by-element fashion, supporting array broadcasting, type casting, and several other standard features. 

In [2]:
#For full documentation
website = "https://docs.scipy.org/doc/numpy/reference/ufuncs.html"
import webbrowser
webbrowser.open(website)

True

In [4]:
# import
import numpy as np

In [5]:
# We create our array
arr = np.arange(1,11)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
#Taking Square Roots
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [7]:
#Calcualting exponential (e^)
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [8]:
# Natural Logarithm 
# The natural logarithm is logarithm in base "e"

np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [9]:
# Base 10 Log

np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

In [10]:
# Get the minimum value

np.min(arr)

1

In [11]:
# Get the maximum value

np.max(arr)

10

### Binary Methods
They require two arrays

In [12]:
#Random array (normal dist)
A = np.random.randn(10)
A

array([ 0.46765932, -0.38015425,  1.89050309, -2.23368445,  0.4334589 ,
       -0.06369986,  0.71434359,  0.59254406,  0.91565705,  0.21227001])

In [13]:
#Random array (normal dist)
B = np.random.randn(10)
B

array([-1.29241196, -0.0102005 , -0.46817586, -0.40798375, -0.78598674,
        0.44343127, -0.55904552,  1.61638979, -0.25823084,  0.00756967])

#### Addition

In [14]:
#Addition
np.add(A,B)

array([-0.82475264, -0.39035476,  1.42232723, -2.6416682 , -0.35252785,
        0.37973141,  0.15529807,  2.20893385,  0.65742621,  0.21983968])

#### Subtraction

In [15]:
np.subtract(A,B)

array([ 1.76007128, -0.36995375,  2.35867895, -1.8257007 ,  1.21944564,
       -0.50713113,  1.27338911, -1.02384573,  1.17388789,  0.20470035])

#### Division

In [16]:
np.divide(A, B)

array([-0.36185004, 37.26818074, -4.03801916,  5.47493483, -0.55148372,
       -0.14365216, -1.27779146,  0.36658488, -3.54588576, 28.04218786])

#### Maximun value

In [17]:
#Finding max or min between two arrays
print(A)
print(B)
np.maximum(A,B)

[ 0.46765932 -0.38015425  1.89050309 -2.23368445  0.4334589  -0.06369986
  0.71434359  0.59254406  0.91565705  0.21227001]
[-1.29241196 -0.0102005  -0.46817586 -0.40798375 -0.78598674  0.44343127
 -0.55904552  1.61638979 -0.25823084  0.00756967]


array([ 0.46765932, -0.0102005 ,  1.89050309, -0.40798375,  0.4334589 ,
        0.44343127,  0.71434359,  1.61638979,  0.91565705,  0.21227001])

In [18]:
# more simple example
np.maximum([10,20,25,40],[11,19,29,44])

array([11, 20, 29, 44])

#### Minimum value

In [19]:
a1 = np.array([10,20,25,40]) 
a2 = np.array([11,19,29,44])

np.minimum(a1, a2)

array([10, 19, 25, 40])

#### sort array

In [22]:
#Create a random array
arr = np.random.randn(5)

#show
arr

array([ 0.75156818,  1.05699075, -1.27252828,  1.11824209,  0.48381273])

In [23]:
#Sort it
arr.sort()

#show
arr

array([-1.27252828,  0.48381273,  0.75156818,  1.05699075,  1.11824209])

#### unique elements

In [25]:
#Lets learn about unique
countries = np.array(['France', 'Germany', 'USA','USA','Mexico','Germany'])

np.unique(countries)

array(['France', 'Germany', 'Mexico', 'USA'], dtype='<U7')

### if in

In [26]:
# in1d test values in one array

np.in1d(['France','USA','Sweden'], countries)

array([ True,  True, False])

# Nice! Lets Exercises!